# .pre-commit-config.yaml
# mypi
repos:
  # Auto cleans Jupyter notebook outputs
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.2.0
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.0" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"
          - "--show-traceback"
          - "--pdb"
        additional_dependencies:
          - sqlalchemy[mypy,asyncio]==2.0.18
          - pydantic
          - types-requests
          - types-python-dateutil
  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E266,E501,E402,W503,E203,E226"
  # black
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        args:
          - --line-length=130

  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
