version: '2'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
          - POSTGRES_DB=docs
          - POSTGRES_USER=fake_user
          - POSTGRES_HOST=fake_host
          - POSTGRES_PASSWORD=fake_password
    web:
        build: '.'
        ports:
            - '5000:5000'
        depends_on:
        - postgres
       